ccflags-y += -I$(srctree)/drivers/xenomai/net/stack/include

obj-$(CONFIG_XENO_DRIVERS_NET_EXP_DRIVERS) += experimental/

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_E1000) += e1000/

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_E1000E) += e1000e/

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_MPC52XX_FEC) += mpc52xx_fec/

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_TULIP) += tulip/

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_IGB) += igb/

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_8139) += rt_8139too.o

rt_8139too-y := 8139too.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_AT91_ETHER) += rt_at91_ether.o

rt_at91_ether-y := at91_ether.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_EEPRO100) += rt_eepro100.o

rt_eepro100-y := eepro100.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_LOOPBACK) += rt_loopback.o

rt_loopback-y := loopback.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_FCC_ENET) += rt_mpc8260_fcc_enet.o

rt_mpc8260_fcc_enet-y := mpc8260_fcc_enet.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_SCC_ENET) += rt_mpc8xx_enet.o

rt_mpc8xx_enet-y := mpc8xx_enet.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_FEC_ENET) += rt_mpc8xx_fec.o

rt_mpc8xx_fec-y := mpc8xx_fec.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_FEC) += rt_fec.o

rt_fec-y := fec.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_NATSEMI) += rt_natsemi.o

rt_natsemi-y := natsemi.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_PCNET32) += rt_pcnet32.o

rt_pcnet32-y := pcnet32.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_SMC91111) += rt_smc91111.o

rt_smc91111-y := smc91111.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_MACB) += rt_macb.o

rt_macb-y := macb.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_VIA_RHINE) += rt_via-rhine.o

rt_via-rhine-y := via-rhine.o

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_R8169) += rt_r8169.o

rt_r8169-y := r8169.o
