ccflags-y += -I$(srctree)/drivers/xenomai/net/stack/include

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_RT2500) += rt2500/

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_E1000_NEW) += e1000/

obj-$(CONFIG_RTNET_DRV_3C59X) += rt_3c59x.o

rt_3c59x-y := 3c59x.o
