ccflags-y += -I$(srctree)/drivers/xenomai/net/stack/include

obj-$(CONFIG_XENO_DRIVERS_NET_RTCFG) += rtcfg.o

rtcfg-y := \
	rtcfg_module.o \
	rtcfg_event.o \
	rtcfg_client_event.o \
	rtcfg_conn_event.o \
	rtcfg_ioctl.o \
	rtcfg_frame.o \
	rtcfg_timer.o \
	rtcfg_file.o \
	rtcfg_proc.o
