# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for the RISC-V Linux kernel
#
obj-$(CONFIG_VECTOR_EMU)	+= softfloat/
obj-$(CONFIG_VECTOR_EMU)	+= insns/
obj-$(CONFIG_VECTOR_EMU)	+= decode.o

clean:
