
obj-$(CONFIG_XENO_DRIVERS_16550A) += xeno_16550A.o
obj-$(CONFIG_XENO_DRIVERS_MPC52XX_UART) += xeno_mpc52xx_uart.o
obj-$(CONFIG_XENO_DRIVERS_IMX_UART) += xeno_imx_uart.o

xeno_16550A-y := 16550A.o
xeno_mpc52xx_uart-y := mpc52xx_uart.o
xeno_imx_uart-y := rt_imx_uart.o
