obj-$(CONFIG_VIDEO_TI_VPE) += ti-vpe.o
obj-$(CONFIG_VIDEO_TI_VIP) += ti-vip.o
obj-$(CONFIG_VIDEO_TI_VPDMA_HELPER) += ti-vpdma.o

ti-vpe-y := vpe.o sc.o csc.o
ti-vip-y := vip.o
ti-vpdma-y := vpdma.o

ccflags-$(CONFIG_VIDEO_TI_VPE_DEBUG) += -DDEBUG
