ccflags-y += -I$(srctree)/drivers/xenomai/net/stack/include

obj-$(CONFIG_XENO_DRIVERS_NET_DRV_RT2500) += rt_rt2x00core.o rt_rt2500pci.o

rt_rt2x00core-y := rt2x00core.o
rt_rt2500pci-y := rt2500pci.o
