# SPDX-License-Identifier: GPL-2.0
#
# TI Keystone SOC drivers
#
obj-$(CONFIG_KEYSTONE_DSP_MEM)		+= keystone_dsp_mem.o
obj-$(CONFIG_KEYSTONE_NAVIGATOR_QMSS)	+= knav_qmss.o
knav_qmss-y := knav_qmss_queue.o knav_qmss_acc.o
obj-$(CONFIG_KEYSTONE_NAVIGATOR_DMA)	+= knav_dma.o
obj-$(CONFIG_AMX3_PM)			+= pm33xx.o
obj-$(CONFIG_WKUP_M3_IPC)		+= wkup_m3_ipc.o
obj-$(CONFIG_TI_SCI_PM_DOMAINS)		+= ti_sci_pm_domains.o
obj-$(CONFIG_TI_K3_NAVSS_RINGACC)	+= k3-navss-ringacc.o
obj-$(CONFIG_TI_K3_NAVSS_DESC_POOL)	+= k3-navss-desc-pool.o
