# SPDX-License-Identifier: GPL-2.0
#
# Make file to build device tree binaries for boards based on
# Texas Instruments Inc processors
#
# Copyright (C) 2016-2021 Texas Instruments Incorporated - https://www.ti.com/
#
# Entries are grouped as per SoC present on the board. Groups are sorted
# alphabetically.

# Boards with AM62x SoC
dtb-$(CONFIG_ARCH_K3) += k3-am625-beagleplay.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am625-beagleplay-csi2-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beagleplay-csi2-tevi-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beagleplay-lincolntech-lcd185-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-sk.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am625-sk-lincolntech-lcd185-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-sk-microtips-mf101hie-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-sk-microtips-mf103hie-lcd2.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-sk-dmtimer-pwm.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-sk-ecap-capture.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62-lp-sk.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am62-lp-sk-nand.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62-lp-sk-lincolntech-lcd185-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62-lp-sk-microtips-mf101hie-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-sk-pwm.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-sk-rpi-hdr-ehrpwm.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-sk-mcspi-loopback.dtbo

# Boards with AM62Ax SoC
k3-am62a7-sk-csi2-imx219-dtbs := k3-am62a7-sk.dtb k3-am62x-sk-csi2-imx219.dtbo
k3-am62a7-sk-fusion-imx390-dtbs := k3-am62a7-sk.dtb \
				   k3-am62a7-sk-fusion.dtbo \
				   k3-fpdlink-imx390-rcm-0-0.dtbo
k3-am62a7-sk-fusion-ov2312-dtbs := k3-am62a7-sk.dtb \
				   k3-am62a7-sk-fusion.dtbo \
				   k3-fpdlink-ov2312-0-0.dtbo
k3-am62a7-sk-ub954-evm-ov2312-dtbs := k3-am62a7-sk.dtb \
				      k3-am62a7-sk-ub954-evm.dtbo \
				      k3-fpdlink-ov2312-0-0.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62a7-sk-csi2-imx219.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am62a7-sk-csi2-ox05b1s.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62a7-sk-e3-max-opp.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62a7-sk-ethernet-dc01.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62a7-sk-fusion-imx390.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am62a7-sk-fusion-ov2312.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am62a7-sk-rpi-hdr-ehrpwm.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62a7-sk-ub954-evm-ov2312.dtb

# Boards with AM62Px SoC
dtb-$(CONFIG_ARCH_K3) += k3-am62p5-sk.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am62p5-sk-dsi-rpi-7inch-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62p5-sk-eqep.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62p5-sk-mcan.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62p5-sk-microtips-mf101hie-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62p5-sk-microtips-mf103hie-lcd2.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62p5-sk-dss-shared-mode.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62p5-sk-rpi-hdr-ehrpwm.dtbo

# Boards with AM64x SoC
dtb-$(CONFIG_ARCH_K3) += k3-am642-evm.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am642-sk.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am642-evm-icssg1-dualemac.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am642-evm-icssg1-dualemac-mii.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am642-evm-nand.dtbo

# Boards with AM65x SoC
dtb-$(CONFIG_ARCH_K3) += k3-am6528-iot2050-basic.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am6528-iot2050-basic-pg2.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am6548-iot2050-advanced.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am6548-iot2050-advanced-pg2.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am654-base-board.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am654-evm-oldi-lcd1evm.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am654-idk.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am654-pcie-usb3.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am654-pcie-usb2.dtbo

# Boards with J7200 SoC
k3-j7200-evm-dtbs := k3-j7200-common-proc-board.dtb k3-j7200-evm-quad-port-eth-exp.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j7200-evm.dtb
dtb-$(CONFIG_ARCH_K3) += k3-j7200-evm-mcspi-loopback.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j7200-evm-virt-mac-client.dtbo

# Boards with J721e SoC
k3-j721e-evm-dtbs := k3-j721e-common-proc-board.dtb k3-j721e-evm-quad-port-eth-exp.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-beagleboneai64.dtb
dtb-$(CONFIG_ARCH_K3) += k3-j721e-beagleboneai64-dsi-rpi-7inch-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-evm.dtb
dtb-$(CONFIG_ARCH_K3) += k3-j721e-evm-csi2-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-evm-fusion.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-evm-gesi-exp-board.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-evm-pcie0-ep.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-evm-virt-mac-client.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-sk.dtb
dtb-$(CONFIG_ARCH_K3) += k3-j721e-sk-csi2-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-sk-csi2-rpi-imx219.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-sk-fusion.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-sk-rpi-hdr-ehrpwm.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-common-proc-board-infotainment.dtbo

# Boards with J721s2 SoC
dtb-$(CONFIG_ARCH_K3) += k3-am68-sk-base-board.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am68-sk-bb-csi2-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am68-sk-bb-rpi-cam-imx219.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am68-sk-fpdlink-fusion.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am68-sk-rpi-hdr-ehrpwm.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am68-sk-som-ddr-mem-carveout.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am68-sk-v3link-fusion.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721s2-common-proc-board.dtb
dtb-$(CONFIG_ARCH_K3) += k3-j721s2-evm-csi2-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721s2-evm-fusion.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721s2-evm-gesi-exp-board.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721s2-evm-pcie1-ep.dtbo

# Boards with J722s SoC
dtb-$(CONFIG_ARCH_K3) += k3-j722s-evm.dtb
dtb-$(CONFIG_ARCH_K3) += k3-j722s-evm-csi2-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j722s-evm-csi2-rpi-cam-imx219.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j722s-evm-csi2-tevi-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j722s-evm-dsi-rpi-7inch-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j722s-evm-fpdlink-fusion.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j722s-evm-microtips-mf101hie-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j722s-evm-v3link-fusion.dtbo

# Boards with J784s4 SoC
dtb-$(CONFIG_ARCH_K3) += k3-am69-sk.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am69-sk-csi2-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am69-sk-ddr-mem-carveout.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am69-sk-csi2-rpi-cam-imx219.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am69-sk-csi2-v3link-fusion.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am69-sk-fpdlink-fusion.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am69-sk-fpdlink-fusion-auxport.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am69-sk-rpi-hdr-ehrpwm.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j784s4-evm.dtb
dtb-$(CONFIG_ARCH_K3) += k3-j784s4-evm-csi2-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j784s4-evm-quad-port-eth-exp1.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j784s4-evm-usxgmii-exp1-exp2.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j784s4-evm-virt-mac-client.dtbo

# Common overlays across AM62 family of boards
dtb-$(CONFIG_ARCH_K3) += k3-am62x-sk-eqep.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62x-sk-csi2-imx219.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62x-sk-csi2-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62x-sk-csi2-tevi-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62x-sk-csi2-v3link-fusion.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62x-sk-hdmi-audio.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62x-sk-hdmi-disable-fastboot.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62x-sk-lpm-wkup-sources.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am62x-sk-mcan.dtbo

# FPDLink Sensors
dtb-$(CONFIG_ARCH_K3) += k3-fpdlink-imx390-rcm-0-0.dtbo \
			 k3-fpdlink-imx390-rcm-0-1.dtbo \
			 k3-fpdlink-imx390-rcm-0-2.dtbo \
			 k3-fpdlink-imx390-rcm-0-3.dtbo \
			 k3-fpdlink-imx390-rcm-1-0.dtbo \
			 k3-fpdlink-imx390-rcm-1-1.dtbo \
			 k3-fpdlink-imx390-rcm-1-2.dtbo \
			 k3-fpdlink-imx390-rcm-1-3.dtbo \
			 k3-fpdlink-imx390-rcm-2-0.dtbo \
			 k3-fpdlink-imx390-rcm-2-1.dtbo \
			 k3-fpdlink-imx390-rcm-2-2.dtbo \
			 k3-fpdlink-imx390-rcm-2-3.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-fpdlink-ov2312-0-0.dtbo \
			 k3-fpdlink-ov2312-0-1.dtbo \
			 k3-fpdlink-ov2312-0-2.dtbo \
			 k3-fpdlink-ov2312-0-3.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-v3link-imx219-0-0.dtbo \
			 k3-v3link-imx219-0-1.dtbo \
			 k3-v3link-imx219-0-2.dtbo \
			 k3-v3link-imx219-0-3.dtbo

dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai.dtb
dtb-$(CONFIG_ARCH_K3) += k3-j722s-beagley-ai-evt.dtb
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-audio.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-can0.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-can1.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-csi0-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-eeprom.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-eth.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-hdmi.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-io-expand.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-lt-lcd185.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-ospi-flash.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-rs485-1.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-rs485-2.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-rtc.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am625-beaglemod-wl1835.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-csi0-imx219.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-csi0-ov5640.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-csi1-imx219.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-dsi-rpi-7inch-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-hat-gpio.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-hdmi-dss0-dpi1.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-i2c-arm.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-lincolntech-185lcd-panel.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-mikroe-eth.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-mikroe-microsd.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-spi0-1cs.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-spi0-2cs.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-am67a-beagley-ai-spidev0.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-edgeai-apps.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j721e-vision-apps.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j722s-edgeai-apps.dtbo
dtb-$(CONFIG_ARCH_K3) += k3-j722s-vision-apps.dtbo

#Enable support for device-tree overlays
DTC_FLAGS_k3-am62-lp-sk += -@
DTC_FLAGS_k3-am625-beaglemod += -@
DTC_FLAGS_k3-am625-beagleplay += -@
DTC_FLAGS_k3-am625-sk += -@
DTC_FLAGS_k3-am625-sk-lpmdemo += -@
DTC_FLAGS_k3-am62a7-sk += -@
DTC_FLAGS_k3-am62a7-sk-fusion += -@
DTC_FLAGS_k3-am62a7-sk-ub954-evm += -@
DTC_FLAGS_k3-am62p5-sk += -@
DTC_FLAGS_k3-am62x-sk-csi2-v3link-fusion += -@
DTC_FLAGS_k3-am654-base-board += -@
DTC_FLAGS_k3-am68-sk-base-board += -@
DTC_FLAGS_k3-am68-sk-fpdlink-fusion += -@
DTC_FLAGS_k3-am68-sk-v3link-fusion += -@
DTC_FLAGS_k3-am69-sk += -@
DTC_FLAGS_k3-am69-sk-csi2-v3link-fusion += -@
DTC_FLAGS_k3-am69-sk-fpdlink-fusion += -@
DTC_FLAGS_k3-am69-sk-fpdlink-fusion-auxport += -@
DTC_FLAGS_k3-j7200-common-proc-board += -@
DTC_FLAGS_k3-j721e-beagleboneai64 += -@
DTC_FLAGS_k3-j721e-common-proc-board += -@
DTC_FLAGS_k3-j721e-evm-fusion += -@
DTC_FLAGS_k3-j721e-sk += -@
DTC_FLAGS_k3-j721e-sk-fusion += -@
DTC_FLAGS_k3-j721s2-common-proc-board += -@
DTC_FLAGS_k3-j721s2-evm-fusion += -@
DTC_FLAGS_k3-am67a-beagley-ai += -@
DTC_FLAGS_k3-j722s-beagley-ai-evt += -@
DTC_FLAGS_k3-j722s-evm += -@
DTC_FLAGS_k3-j722s-evm-fpdlink-fusion += -@
DTC_FLAGS_k3-j722s-evm-v3link-fusion += -@
DTC_FLAGS_k3-j784s4-evm += -@
DTC_FLAGS_k3-am642-evm += -@
