# SPDX-License-Identifier: GPL-2.0

obj-$(CONFIG_THEAD_CLK) += \
	clk.o

obj-$(CONFIG_CLK_LIGHT_MPW)  += clk-light-mpw.o
obj-$(CONFIG_CLK_LIGHT_FM)  += clk-light-fm.o
obj-$(CONFIG_CLK_LIGHT_FM)  += gate/
