
ccflags-y += -I$(srctree)/drivers/xenomai/analogy

obj-$(CONFIG_XENO_DRIVERS_ANALOGY_NI_MITE) += analogy_ni_mite.o
obj-$(CONFIG_XENO_DRIVERS_ANALOGY_NI_TIO) += analogy_ni_tio.o
obj-$(CONFIG_XENO_DRIVERS_ANALOGY_NI_MIO) += analogy_ni_mio.o
obj-$(CONFIG_XENO_DRIVERS_ANALOGY_NI_PCIMIO) += analogy_ni_pcimio.o
obj-$(CONFIG_XENO_DRIVERS_ANALOGY_NI_670x) += analogy_ni_670x.o
obj-$(CONFIG_XENO_DRIVERS_ANALOGY_NI_660x) += analogy_ni_660x.o

analogy_ni_mite-y := mite.o
analogy_ni_tio-y := tio_common.o
analogy_ni_mio-y := mio_common.o
analogy_ni_pcimio-y := pcimio.o
analogy_ni_670x-y := ni_670x.o
analogy_ni_660x-y := ni_660x.o
