/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (C) 2022 Alibaba Group Holding Limited.
 */

#ifndef LIGHT_VOSYS_H
#define LIGHT_VOSYS_H

#define LIGHT_CLKGEN_AXI4_VO_PCLK			0
#define LIGHT_CLKGEN_IOPMP_VOSYS_DPU_PCLK		1
#define LIGHT_CLKGEN_IOPMP_VOSYS_DPU1_PCLK		2
#define LIGHT_CLKGEN_IOPMP_VOSYS_GPU_PCLK		3
#define LIGHT_CLKGEN_HDMI_PCLK				4
#define LIGHT_CLKGEN_MIPIDSI0_PCLK			5
#define LIGHT_CLKGEN_MIPIDSI1_PCLK			6
#define LIGHT_CLKGEN_AXI4_VO_ACLK			7
#define LIGHT_CLKGEN_IOPMP_GPU_ACLK			8
#define LIGHT_CLKGEN_IOPMP_DPU_ACLK			9
#define LIGHT_CLKGEN_IOPMP_DPU1_ACLK			10
#define LIGHT_CLKGEN_X2H_DPU_ACLK			11
#define LIGHT_CLKGEN_X2H_DPU1_ACLK			12
#define LIGHT_CLKGEN_MIPIDSI0_PIXCLK			13
#define LIGHT_CLKGEN_HDMI_PIXCLK			14
#define LIGHT_CLKGEN_MIPIDSI1_PIXCLK			15
#define LIGHT_CLKGEN_HDMI_SFR_CLK			16
#define LIGHT_CLKGEN_HDMI_CEC_CLK			17
#define LIGHT_CLKGEN_HDMI_I2S_CLK			18
#define LIGHT_CLKGEN_MIPIDSI0_CFG_CLK			19
#define LIGHT_CLKGEN_MIPIDSI1_CFG_CLK			20
#define LIGHT_CLKGEN_MIPIDSI0_REFCLK			21
#define LIGHT_CLKGEN_MIPIDSI1_REFCLK			22
#define LIGHT_CLKGEN_GPU_CORE_CLK			23
#define LIGHT_CLKGEN_GPU_CFG_ACLK			24
#define LIGHT_CLKGEN_DPU_HCLK				25
#define LIGHT_CLKGEN_DPU_ACLK				26
#define LIGHT_CLKGEN_DPU_CCLK				27
#define LIGHT_CLKGEN_DPU_PIXCLK0			28
#define LIGHT_CLKGEN_DPU_PIXCLK1                        29
#define LIGHT_CLKGEN_VOSYS_CLK_END			30

#endif
