# SPDX-License-Identifier: GPL-2.0
obj-$(CONFIG_WLCORE)			+= wlcore/
obj-$(CONFIG_WL12XX)			+= wl12xx/
obj-$(CONFIG_WL1251)			+= wl1251/
obj-$(CONFIG_WL18XX)			+= wl18xx/
obj-$(CONFIG_CC33XX)			+= cc33xx/

# small builtin driver bit
obj-$(CONFIG_WILINK_PLATFORM_DATA)	+= wilink_platform_data.o
