ccflags-y += -I$(srctree)/drivers/xenomai/net/stack/include

obj-$(CONFIG_XENO_DRIVERS_NET_ADDON_RTCAP) += rtcap.o

rtcap-y := cap.o

obj-$(CONFIG_XENO_DRIVERS_NET_ADDON_PROXY) += rtnetproxy.o

rtnetproxy-y := proxy.o
