# SPDX-License-Identifier: GPL-2.0
# mikroBUS Core

mikrobus-y :=	mikrobus_core.o	mikrobus_manifest.o
mikrobus_port-y :=	mikrobus_port.o
obj-$(CONFIG_MIKROBUS) += mikrobus.o
obj-$(CONFIG_MIKROBUS) += mikrobus_port.o