# Generic voltage domain
obj-$(CONFIG_VOLTAGE_DOMAIN)	+= core.o

# Hardware specific voltage domain
# please keep this section sorted lexicographically by file/directory path name
obj-$(CONFIG_VOLTAGE_DOMAIN_OMAP)	+= voltdm_omap.o
