#
# Makefile for CBUS.
#

obj-$(CONFIG_CBUS)		+= cbus.o
obj-$(CONFIG_CBUS_TAHVO)	+= tahvo.o
obj-$(CONFIG_CBUS_RETU)		+= retu.o
obj-$(CONFIG_CBUS_TAHVO_USB)	+= tahvo-usb.o
obj-$(CONFIG_CBUS_RETU_POWERBUTTON) += retu-pwrbutton.o
obj-$(CONFIG_CBUS_RETU_RTC)	+= retu-rtc.o
obj-$(CONFIG_CBUS_RETU_WDT)	+= retu-wdt.o
obj-$(CONFIG_CBUS_TAHVO_USER)	+= tahvo-user.o
obj-$(CONFIG_CBUS_RETU_USER)	+= retu-user.o
obj-$(CONFIG_CBUS_RETU_HEADSET)	+= retu-headset.o
