/*
 * AM33XX SDMA channel definitions
 *
 * This file is automatically generated from the AM33XX hardware databases.
 *
 * Copyright (C) 2011 Texas Instruments Incorporated - http://www.ti.com/
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation version 2.
 *
 * This program is distributed "as is" WITHOUT ANY WARRANTY of any
 * kind, whether express or implied; without even the implied warranty
 * of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */

#ifndef __ARCH_ARM_MACH_OMAP2_AM33XX_DMA_H
#define __ARCH_ARM_MACH_OMAP2_AM33XX_DMA_H


#define AM33XX_DMA_ICSS0_7				0
#define AM33XX_DMA_ICSS0_6				1
#define AM33XX_DMA_MMCHS1_W				2
#define AM33XX_DMA_MMCHS1_R				3
#define AM33XX_DMA_AESEIP36T0_CTXIN			4
#define AM33XX_DMA_AESEIP36T0_DIN			5
#define AM33XX_DMA_AESEIP36T0_DOUT			6
#define AM33XX_DMA_AESEIP36T0_CTXOUT			7
#define AM33XX_DMA_MCASP0_X				8
#define AM33XX_DMA_MCASP0_R				9
#define AM33XX_DMA_MCASP1_X				10
#define AM33XX_DMA_MCASP1_R				11
#define AM33XX_DMA_MCASP2_X				12
#define AM33XX_DMA_MCASP2_R				13
#define AM33XX_DMA_PWMSS0_EPWM				14
#define AM33XX_DMA_PWMSS1_EPWM				15
#define AM33XX_DMA_SPIOCP0_CH0W				16
#define AM33XX_DMA_SPIOCP0_CH0R				17
#define AM33XX_DMA_SPIOCP0_CH1W				18
#define AM33XX_DMA_SPIOCP0_CH1R				19
#define AM33XX_DMA_SPIOCP3_CH1W				20
#define AM33XX_DMA_SPIOCP3_CH1R				21
#define AM33XX_DMA_GPIO					22
#define AM33XX_DMA_GPIO1				23
#define AM33XX_DMA_MMCHS0_W				24
#define AM33XX_DMA_MMCHS0_R				25
#define AM33XX_DMA_UART0_0				26
#define AM33XX_DMA_UART0_1				27
#define AM33XX_DMA_UART1_0				28
#define AM33XX_DMA_UART1_1				29
#define AM33XX_DMA_UART2_0				30
#define AM33XX_DMA_UART2_1				31
#define AM33XX_DMA_DESEIP16T0_IN			32
#define AM33XX_DMA_DESEIP16T0				33
#define AM33XX_DMA_DESEIP16T0_OUT			34
#define AM33XX_DMA_SHAEIP57T0_CTXIN			35
#define AM33XX_DMA_SHAEIP57T0_DIN			36
#define AM33XX_DMA_SHAEIP57T0_CTXOUT			37
#define AM33XX_DMA_PWMSS0_ECAP				38
#define AM33XX_DMA_PWMSS1_ECAP				39
#define AM33XX_DMA_DCAN_1				40
#define AM33XX_DMA_DCAN_2				41
#define AM33XX_DMA_SPIOCP1_CH0W				42
#define AM33XX_DMA_SPIOCP1_CH0R				43
#define AM33XX_DMA_SPIOCP1_CH1W				44
#define AM33XX_DMA_SPIOCP1_CH1R				45
#define AM33XX_DMA_PWMSS0_EQEP				46
#define AM33XX_DMA_DCAN_3				47
#define AM33XX_DMA_TIMER_4				48
#define AM33XX_DMA_TIMER_5				49
#define AM33XX_DMA_TIMER_6				50
#define AM33XX_DMA_TIMER_7				51
#define AM33XX_DMA_GPM					52
#define AM33XX_DMA_ADC0					53
#define AM33XX_DMA_PWMSS1_EQEP				56
#define AM33XX_DMA_ADC1					57
#define AM33XX_DMA_MSHSI2COCP0_TX			58
#define AM33XX_DMA_MSHSI2COCP0_RX			59
#define AM33XX_DMA_MSHSI2COCP1_TX			60
#define AM33XX_DMA_MSHSI2COCP1_RX			61
#define AM33XX_DMA_PWMSS2_ECAP				62
#define AM33XX_DMA_PWMSS2_EPW				63
#define AM33XX_DMA_MMCHS2_W				64	/* xBar */
#define AM33XX_DMA_MMCHS2_R				65	/* xBar */

#endif
