# SPDX-License-Identifier: GPL-2.0
#
# Makefile for light backend drivers
#

obj-$(CONFIG_LIGHT_MAILBOX)	+= light_mailbox/
obj-$(CONFIG_LIGHT_BLK)		+= light_blk/
obj-$(CONFIG_LIGHT_NET)		+= light_net/
