# rstctl support

ccflags-$(CONFIG_DEBUG_RSTCTL)	+= -DDEBUG

obj-$(CONFIG_RSTCTL)			+= core.o
obj-$(CONFIG_RSTCTL_TEST)		+= rstctl-test.o
obj-$(CONFIG_RSTCTL_TEST_CONSUMER)	+= rstctl-test-consumer.o
obj-$(CONFIG_RSTCTL_GPIO)		+= rstctl-gpio.o
