
ccflags-y += -I$(srctree)/drivers/xenomai/analogy

obj-$(CONFIG_XENO_DRIVERS_ANALOGY_8255) += analogy_8255.o

obj-$(CONFIG_XENO_DRIVERS_ANALOGY_PARPORT) += analogy_parport.o

analogy_8255-y := 8255.o

analogy_parport-y := parport.o
