obj-$(CONFIG_RESET_CONTROLLER) += core.o
obj-$(CONFIG_ARCH_SOCFPGA) += reset-socfpga.o
obj-$(CONFIG_ARCH_BERLIN) += reset-berlin.o
obj-$(CONFIG_ARCH_SUNXI) += reset-sunxi.o
obj-$(CONFIG_ARCH_STI) += sti/

obj-$(CONFIG_SYSCON_RESET) += reset-syscon.o
obj-$(CONFIG_TI_SCI_RESET) += reset-ti-sci.o
